##
# site settings
theme              : jekyll-theme-minimal
locale             : "en-US"
title              : "Felippe Mariano Colombari"
title_separator    : "-"
name               : &name "Felippe Mariano Colombari"
description        : &description "Computational Chemist"
url                : https://colombarifm.github.io
baseurl            : ""
repository         : "colombarifm/colombarifm.github.io"

author:
  name          : Felippe Mariano Colombari
  location      : Campinas, Brasil
  googlescholar  : https://scholar.google.com.br/citations?user=hcTVynIAAAAJ&hl=pt-BR




