##


author:
  name          : Felippe Mariano Colombari
  location      : Campinas, Brasil
  googlescholar  : https://scholar.google.com.br/citations?user=hcTVynIAAAAJ&hl=pt-BR



theme: jekyll-theme-slate
