##
# site settings
theme              : jekyll-theme-minimal
locale             : "en-US"
title              : "Felippe Mariano Colombari"
title_separator    : "-"
name               : &name "Felippe Mariano Colombari"
description        : &description "Computational Chemist"
url                : https://colombarifm.github.io
baseurl            : ""
repository         : "colombarifm/colombarifm.github.io"

author:
  name             : Felippe Mariano Colombari
  location         : Campinas, Brasil
  googlescholar    : https://scholar.google.com.br/citations?user=hcTVynIAAAAJ&hl=pt-BR
  email            : ""
  researchgate     : ""
  github           : "colombarifm"
  orcid            : ""

# conversion
markdown           : kramdown
highlighter        : rouge
lsi                : false
excerpt_separator  : "\n\n"
incremental        : false

# markdown processing
kramdown:
  input:           : GFM
  hard_wrap        : false
  auto_ids         : true
  footnote_nr      : 1
  entity_output    : as_char
  toc_levels       : 1..6
  smart_quotes     : lsquo, rsquo, ldquo, rdquo
  enable_coderay   : false

compress_html:
  clippings: all
  ignore:
    envs: development


